services:
  backend:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
